name: kryptex

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kryptex
    container_name: kryptex
    ports:
      - "127.0.0.1:443:8000"
    volumes:
      - ./database:/app/database
      - ./certs:/certs:ro
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput && 
             gunicorn project.wsgi:application --bind 0.0.0.0:8000 --certfile=/certs/cert.pem --keyfile=/certs/key.pem"
    restart: unless-stopped
