# Generated by Django 6.0 on 2025-12-17 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Serviço')),
                ('username', models.CharField(max_length=100, verbose_name='Usuário/Email')),
                ('encrypted_password', models.TextField(blank=True, null=True, verbose_name='Senha Criptografada')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciais',
            },
        ),
    ]
