# Generated by Django 6.0 on 2025-12-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
